version: '3.4'

services:
  petbookserver:
    image: petbookserver
    build:
      network_mode: host
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
